### ISSUE TITLE
As a user, I want to follow another user

### ISSUE THREAD

**Issue by EjazaliRezayi** [jbwaring/Instaframe#6]
Description: As a user, I want to be able to follow another user so that I can see his posts in the future.

Steps:

- Unfollow: user can unfollow another user he followed once
- User can see his/her number of followers and the followers' usernames
- User can see the posts of who the user follows based on the post's recency
- Follow schema in database
- User can search for users to follow

Priority: HIGH

**Comment by Kastor14** [comment]
We can follow! looks good no bugs!
